/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cvut.fel.aic.shortestpaths;

public class shortestPathsJNI {
  public final static native void CHDistanceQueryManagerAPI_initializeCH(long jarg1, CHDistanceQueryManagerAPI jarg1_, String jarg2, String jarg3);
  public final static native long CHDistanceQueryManagerAPI_distanceQuery(long jarg1, CHDistanceQueryManagerAPI jarg1_, java.math.BigInteger jarg2, java.math.BigInteger jarg3);
  public final static native void CHDistanceQueryManagerAPI_clearStructures(long jarg1, CHDistanceQueryManagerAPI jarg1_);
  public final static native long new_CHDistanceQueryManagerAPI();
  public final static native void delete_CHDistanceQueryManagerAPI(long jarg1);
  public final static native void TNRDistanceQueryManagerAPI_initializeTNR(long jarg1, TNRDistanceQueryManagerAPI jarg1_, String jarg2, String jarg3);
  public final static native long TNRDistanceQueryManagerAPI_distanceQuery(long jarg1, TNRDistanceQueryManagerAPI jarg1_, java.math.BigInteger jarg2, java.math.BigInteger jarg3);
  public final static native void TNRDistanceQueryManagerAPI_clearStructures(long jarg1, TNRDistanceQueryManagerAPI jarg1_);
  public final static native long new_TNRDistanceQueryManagerAPI();
  public final static native void delete_TNRDistanceQueryManagerAPI(long jarg1);
  public final static native void TNRAFDistanceQueryManagerAPI_initializeTNRAF(long jarg1, TNRAFDistanceQueryManagerAPI jarg1_, String jarg2, String jarg3);
  public final static native long TNRAFDistanceQueryManagerAPI_distanceQuery(long jarg1, TNRAFDistanceQueryManagerAPI jarg1_, java.math.BigInteger jarg2, java.math.BigInteger jarg3);
  public final static native void TNRAFDistanceQueryManagerAPI_clearStructures(long jarg1, TNRAFDistanceQueryManagerAPI jarg1_);
  public final static native long new_TNRAFDistanceQueryManagerAPI();
  public final static native void delete_TNRAFDistanceQueryManagerAPI(long jarg1);
}
