/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cvut.fel.aic.contractionhierarchies;

public class contractionHierarchiesJNI {
  public final static native void IntegerDistanceQueryManagerAPI_initializeCH(long jarg1, IntegerDistanceQueryManagerAPI jarg1_, String jarg2);
  public final static native long IntegerDistanceQueryManagerAPI_distanceQuery(long jarg1, IntegerDistanceQueryManagerAPI jarg1_, long jarg2, long jarg3);
  public final static native void IntegerDistanceQueryManagerAPI_clearStructures(long jarg1, IntegerDistanceQueryManagerAPI jarg1_);
  public final static native long new_IntegerDistanceQueryManagerAPI();
  public final static native void delete_IntegerDistanceQueryManagerAPI(long jarg1);
  public final static native void IntegerDistanceQueryManagerWithMappingAPI_initializeCH(long jarg1, IntegerDistanceQueryManagerWithMappingAPI jarg1_, String jarg2, String jarg3);
  public final static native long IntegerDistanceQueryManagerWithMappingAPI_distanceQuery(long jarg1, IntegerDistanceQueryManagerWithMappingAPI jarg1_, java.math.BigInteger jarg2, java.math.BigInteger jarg3);
  public final static native void IntegerDistanceQueryManagerWithMappingAPI_clearStructures(long jarg1, IntegerDistanceQueryManagerWithMappingAPI jarg1_);
  public final static native long new_IntegerDistanceQueryManagerWithMappingAPI();
  public final static native void delete_IntegerDistanceQueryManagerWithMappingAPI(long jarg1);
  public final static native void FPointDistanceQueryManagerAPI_initializeCH(long jarg1, FPointDistanceQueryManagerAPI jarg1_, String jarg2);
  public final static native double FPointDistanceQueryManagerAPI_distanceQuery(long jarg1, FPointDistanceQueryManagerAPI jarg1_, long jarg2, long jarg3);
  public final static native void FPointDistanceQueryManagerAPI_clearStructures(long jarg1, FPointDistanceQueryManagerAPI jarg1_);
  public final static native long new_FPointDistanceQueryManagerAPI();
  public final static native void delete_FPointDistanceQueryManagerAPI(long jarg1);
  public final static native void FPointDistanceQueryManagerWithMappingAPI_initializeCH(long jarg1, FPointDistanceQueryManagerWithMappingAPI jarg1_, String jarg2, String jarg3);
  public final static native double FPointDistanceQueryManagerWithMappingAPI_distanceQuery(long jarg1, FPointDistanceQueryManagerWithMappingAPI jarg1_, java.math.BigInteger jarg2, java.math.BigInteger jarg3);
  public final static native void FPointDistanceQueryManagerWithMappingAPI_clearStructures(long jarg1, FPointDistanceQueryManagerWithMappingAPI jarg1_);
  public final static native long new_FPointDistanceQueryManagerWithMappingAPI();
  public final static native void delete_FPointDistanceQueryManagerWithMappingAPI(long jarg1);
}
