/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cz.cvut.fel.aic.contractionhierarchies;

public class IntegerDistanceQueryManagerAPI {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntegerDistanceQueryManagerAPI(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntegerDistanceQueryManagerAPI obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        contractionHierarchiesJNI.delete_IntegerDistanceQueryManagerAPI(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void initializeCH(String chFile) {
    contractionHierarchiesJNI.IntegerDistanceQueryManagerAPI_initializeCH(swigCPtr, this, chFile);
  }

  public long distanceQuery(long source, long target) {
    return contractionHierarchiesJNI.IntegerDistanceQueryManagerAPI_distanceQuery(swigCPtr, this, source, target);
  }

  public void clearStructures() {
    contractionHierarchiesJNI.IntegerDistanceQueryManagerAPI_clearStructures(swigCPtr, this);
  }

  public IntegerDistanceQueryManagerAPI() {
    this(contractionHierarchiesJNI.new_IntegerDistanceQueryManagerAPI(), true);
  }

}
