
class Comparison:

    def __init__(self, properties: dict = None):
        self.experiment_1_name = properties.get("experiment_1_name")
        self.experiment_1_dir = properties.get("experiment_1_dir")
        self.experiment_2_name = properties.get("experiment_2_name")
        self.experiment_2_dir = properties.get("experiment_2_dir")
        self.experiment_3_name = properties.get("experiment_3_name")
        self.experiment_3_dir = properties.get("experiment_3_dir")
        self.experiment_4_name = properties.get("experiment_4_name")
        self.experiment_4_dir = properties.get("experiment_4_dir")
        self.experiment_5_name = properties.get("experiment_5_name")
        self.experiment_5_dir = properties.get("experiment_5_dir")
        self.experiment_6_name = properties.get("experiment_6_name")
        self.experiment_6_dir = properties.get("experiment_6_dir")
        self.experiment_7_name = properties.get("experiment_7_name")
        self.experiment_7_dir = properties.get("experiment_7_dir")
        self.experiment_8_name = properties.get("experiment_8_name")
        self.experiment_8_dir = properties.get("experiment_8_dir")
        self.experiment_9_name = properties.get("experiment_9_name")
        self.experiment_9_dir = properties.get("experiment_9_dir")
        self.experiment_10_name = properties.get("experiment_10_name")
        self.experiment_10_dir = properties.get("experiment_10_dir")
        self.experiment_11_name = properties.get("experiment_11_name")
        self.experiment_11_dir = properties.get("experiment_11_dir")
        self.experiment_12_name = properties.get("experiment_12_name")
        self.experiment_12_dir = properties.get("experiment_12_dir")
        self.experiment_13_name = properties.get("experiment_13_name")
        self.experiment_13_dir = properties.get("experiment_13_dir")
        self.experiment_14_name = properties.get("experiment_14_name")
        self.experiment_14_dir = properties.get("experiment_14_dir")
        self.experiment_15_name = properties.get("experiment_15_name")
        self.experiment_15_dir = properties.get("experiment_15_dir")
        self.experiment_16_name = properties.get("experiment_16_name")
        self.experiment_16_dir = properties.get("experiment_16_dir")
        pass
